import "server-only";
import { getCloudflareContext } from "@opennextjs/cloudflare";
import { siteConfig } from "@/lib/site";
import packageJson from "../../package.json";

/**
 * What is running, in one place.
 *
 * Served by `GET /api/v1/version` (and the `/version` alias). Everything here is
 * derived from a file that already exists — nothing is hand-maintained twice:
 *
 *   app version  → `package.json#version`, documented in `CHANGELOG.md`
 *   API version  → `API_VERSION` below, mirroring `openapi.yaml#info.version`
 *   environment  → `APP_ENV` (set per env in wrangler.toml, same var the logger tags with)
 *   build        → Cloudflare's `version_metadata` binding (the deployed Worker version)
 *
 * `tests/unit/version.test.ts` fails if any of those drift apart, so the
 * endpoint can't report a version the changelogs don't describe.
 *
 * **Server-only on purpose**: importing `package.json` pulls the whole file
 * (including the dependency list) into whatever bundle imports this module. A
 * client component that needs the version should take it as a prop from a
 * server component.
 */

/** The app release, straight from `package.json` (see `CHANGELOG.md`). */
export const APP_VERSION: string = packageJson.version;

/**
 * Version of the `/api/v1` REST contract — the same value as `info.version` in
 * `_developer/flutter/openapi.yaml`. Every API change bumps this **and** the
 * spec, the "API spec version" line in `01-api-reference.md`, and adds a
 * `_developer/flutter/_changelog.md` entry.
 */
export const API_VERSION = "5.9.3";

/** Which deployment answered: prod, beta, or a local/dev run. */
export type DeployEnvironment = "production" | "beta" | "development";

/** Identity of the deployed Worker version, when the runtime exposes it. */
export type BuildInfo = {
  /** Cloudflare Worker version id — quote it in a bug report. */
  id: string;
  /** When that version was uploaded (ISO 8601), or null if unparseable. */
  deployedAt: string | null;
};

/**
 * The public version payload. Deliberately limited to facts that are already
 * public (the source is AGPL and on GitHub) and useful to a client or a support
 * ticket. It carries **no** runtime internals — no dependency versions, no
 * hostnames, no region, no env var names, no database or storage state.
 */
export type VersionInfo = {
  name: string;
  version: string;
  apiVersion: string;
  environment: DeployEnvironment;
  build: BuildInfo | null;
  changelog: { app: string; api: string };
};

const REPO_BLOB = `${siteConfig.links.github}/blob/master`;

/**
 * `APP_ENV` is set per environment in wrangler.toml ("production" / "beta") and
 * unset everywhere else. Anything unrecognized reads as a local run rather than
 * being echoed back — the value ships to clients, so it stays a closed set.
 */
function resolveEnvironment(): DeployEnvironment {
  const env = process.env.APP_ENV;
  return env === "production" || env === "beta" ? env : "development";
}

/** Shape of the `version_metadata` binding (see `resolveBuild`). */
type VersionMetadata = { id?: string; tag?: string; timestamp?: string };

/**
 * Deploy identity from Cloudflare's `version_metadata` binding — the one detail
 * a version number can't give you when two deploys share a version.
 *
 * Absent outside a Worker request (tests, build, `next dev` without the
 * binding) and until the wrangler.toml change is deployed, so it degrades to
 * `null` rather than throwing. Read through a local type instead of
 * `CloudflareEnv`: that interface is regenerated by `cf-typegen` and types the
 * binding as always-present, which isn't true of a not-yet-deployed Worker.
 */
function resolveBuild(): BuildInfo | null {
  let meta: VersionMetadata | undefined;
  try {
    const env = getCloudflareContext().env as {
      CF_VERSION_METADATA?: VersionMetadata;
    };
    meta = env.CF_VERSION_METADATA;
  } catch {
    return null;
  }
  if (!meta?.id) return null;
  const uploadedAt = meta.timestamp ? new Date(meta.timestamp) : null;
  return {
    id: meta.id,
    deployedAt:
      uploadedAt && !Number.isNaN(uploadedAt.getTime())
        ? uploadedAt.toISOString()
        : null,
  };
}

/** Build the payload returned by `GET /api/v1/version` and `GET /version`. */
export function getVersionInfo(): VersionInfo {
  return {
    name: siteConfig.name,
    version: APP_VERSION,
    apiVersion: API_VERSION,
    environment: resolveEnvironment(),
    build: resolveBuild(),
    changelog: {
      app: `${REPO_BLOB}/CHANGELOG.md`,
      api: `${REPO_BLOB}/_developer/flutter/_changelog.md`,
    },
  };
}
