import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated Cloudflare/OpenNext output:
    ".open-next/**",
    ".wrangler/**",
    // Generated test coverage report:
    "coverage/**",
    // Generated by /design-sync (see .design-sync/NOTES.md): the converter's
    // bundle output, its staged scripts, and the emitted declaration tree.
    // All three are gitignored build artifacts, not source.
    "ds-bundle/**",
    ".ds-sync/**",
    "dist/**",
    ".design-sync/.cache/**",
  ]),
]);

export default eslintConfig;
