#!/usr/bin/env node
// Regenerates the two inputs the /design-sync converter needs from this repo.
// Referenced as `buildCmd` in config.json — run it before package-build.mjs.
//
// SpendChat is a Next.js app, not a published component package, so there is
// no `dist/` to bundle. This script stands in for that build:
//
//   1. `.design-sync/ds-entry.ts` — a curated barrel of the browser-safe
//      component surface. Files that import server actions, `@/lib/queries`,
//      `@/lib/db` or `@/lib/firebase` at runtime are excluded: esbuild would
//      drag `pg`/`drizzle`/node builtins into a browser bundle. `import type`
//      references to those modules are fine — they erase at compile time.
//   2. `.design-sync/.cache/tailwind.css` — the compiled stylesheet. The app's
//      `globals.css` is Tailwind v4 *source*; without this step every preview
//      card renders with no utilities and no `@theme` tokens.
//   3. `.design-sync/.cache/stubs/actions/*.ts` — no-op stand-ins for the
//      `"use server"` modules under `src/actions/`, wired in by the `paths`
//      map in `tsconfig.sync.json`. Shells like AppSidebar and
//      TransactionComposer import server actions transitively; bundling the
//      real modules would pull `pg`, `drizzle` and node builtins into a
//      browser bundle. This mirrors production: Next replaces a `"use server"`
//      import with an RPC reference, so the browser never holds those bodies
//      either. Design-system consumers wire their own handlers.
//
// Adding a component to the design system = add its file to FILES below and
// its exported name to `componentSrcMap` in config.json.

import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), '..');
process.chdir(REPO);

// Every shadcn/ui primitive, plus the presentational SpendChat surfaces.
const UI = readdirSync('src/components/ui')
  .filter((f) => f.endsWith('.tsx'))
  .sort()
  .map((f) => `src/components/ui/${f}`);

const REST = [
  'app/app-sidebar', 'app/app-topbar', 'app/bottom-nav', 'app/category-pie-chart',
  'app/category-row', 'app/chat-skeleton', 'app/control-hint', 'app/currency-combobox',
  'app/date-range-filter', 'app/day-divider', 'app/entry-mode-toggle', 'app/month-divider',
  'app/profile-switcher', 'app/settings-nav', 'app/shortcut-list', 'app/transaction-bubble',
  'app/transaction-composer', 'app/transaction-filters', 'app/transactions-skeleton',
  'app/type-filter-options', 'app/viewer-notice', 'app/voice-mic', 'app/files/storage-ring',
  'app/attachments/attachment-tile', 'app/attachments/attachment-list',
  'app/attachments/attachment-squares',
  'logo', 'theme-toggle', 'icons/github', 'marketing/site-nav', 'marketing/site-footer',
  // Bundled but not carded: TransactionComposer calls usePendingMessages(),
  // which throws outside this provider. It ships in the bundle so the preview
  // wrapper (and any design composing the composer) can supply the context.
  'app/pending-messages',
  // Bundled but not carded: the app's real theme root. It is nested inside
  // the preview provider below, and it is what a design built from this system
  // should wrap its own tree in.
  'theme-provider',
].map((p) => `src/components/${p}.tsx`);

const FILES = [...UI, ...REST];

// `export *` silently drops a name exported by two files — fail loudly instead.
const owner = new Map();
const dupes = [];
for (const f of FILES) {
  const src = readFileSync(f, 'utf8');
  const names = new Set();
  for (const m of src.matchAll(/export\s+(?:const|function|class)\s+([A-Za-z_$][\w$]*)/g)) names.add(m[1]);
  for (const m of src.matchAll(/export\s*\{([^}]*)\}/g)) {
    for (const part of m[1].split(',')) {
      const t = part.trim();
      if (!t) continue;
      const as = /\bas\s+([\w$]+)$/.exec(t);
      names.add(as ? as[1] : t.replace(/^type\s+/, ''));
    }
  }
  for (const n of names) {
    if (owner.has(n)) dupes.push(`${n}: ${owner.get(n)} vs ${f}`);
    else owner.set(n, f);
  }
}
if (dupes.length) {
  console.error(`[REGEN] duplicate exports across entry files:\n  ${dupes.join('\n  ')}`);
  process.exit(1);
}

writeFileSync(
  '.design-sync/ds-entry.ts',
  '// GENERATED by .design-sync/regen.mjs — do not edit by hand.\n' +
    '// Curated browser-safe surface of the SpendChat component library.\n' +
    // Must stay first: ES module imports evaluate in source order, and the
    // shim has to install `globalThis.process` before Next's client runtime
    // reads `process.env.*` at module scope. See browser-shim.ts.
    'import "./browser-shim";\n' +
    FILES.map((f) => `export * from "@/${f.replace(/^src\//, '').replace(/\.tsx$/, '')}";`).join('\n') +
    '\nexport * from "./preview-providers";\n',
);

// ── server-action stubs ──────────────────────────────────────────────────
const STUB_DIR = '.design-sync/.cache/stubs/actions';
mkdirSync(STUB_DIR, { recursive: true });
let stubCount = 0;
for (const f of readdirSync('src/actions').filter((n) => n.endsWith('.ts'))) {
  const src = readFileSync(`src/actions/${f}`, 'utf8');
  const names = new Set();
  for (const m of src.matchAll(/export\s+(?:async\s+)?(?:function|const|let|var|class)\s+([A-Za-z_$][\w$]*)/g)) {
    names.add(m[1]);
  }
  for (const m of src.matchAll(/export\s*\{([^}]*)\}/g)) {
    for (const part of m[1].split(',')) {
      const t = part.trim();
      if (!t || t.startsWith('type ')) continue;
      const as = /\bas\s+([\w$]+)$/.exec(t);
      names.add(as ? as[1] : t);
    }
  }
  // Return type is `any`, not `never`: callers destructure the real action's
  // result (`{ ok, error, count }`), and `never` would make every one of those
  // reads a declaration-emit error.
  const body = [...names]
    .sort()
    .map(
      (n) =>
        `// eslint-disable-next-line @typescript-eslint/no-explicit-any\n` +
        `export async function ${n}(..._args: unknown[]): Promise<any> {\n` +
        `  throw new Error(\n` +
        `    "${n}() is a server action. The SpendChat design-system bundle ships a stub — " +\n` +
        `      "wire your own handler when composing with this component.",\n` +
        `  );\n}`,
    )
    .join('\n\n');
  writeFileSync(
    `${STUB_DIR}/${f}`,
    `// GENERATED by .design-sync/regen.mjs — no-op stand-in for src/actions/${f}.\n` +
      `// See the header of regen.mjs for why these are stubbed.\n\n` +
      (body || 'export {};') +
      '\n',
  );
  stubCount += names.size;
}

execFileSync(
  'npx',
  ['--yes', '@tailwindcss/cli@4', '-i', '.design-sync/tailwind-entry.css', '-o', '.design-sync/.cache/tailwind.css'],
  { stdio: 'inherit' },
);

// ── declaration tree ─────────────────────────────────────────────────────
// The converter reads `<Name>Props` from the package's shipped .d.ts; with no
// declarations every emitted contract collapses to `[key: string]: unknown`,
// which is what the claude.ai/design agent would then code against. `tsc`
// exits non-zero on pre-existing type errors in files outside the card set —
// declarations still emit, so the status is reported, not fatal.
rmSync('dist/types', { recursive: true, force: true });
try {
  execFileSync('npx', ['tsc', '-p', '.design-sync/tsconfig.emit.json'], { stdio: 'pipe' });
} catch (e) {
  const lines = String(e.stdout ?? '').trim().split('\n').filter(Boolean);
  console.error(`[REGEN] tsc reported ${lines.length} diagnostic(s) — declarations still emitted`);
}

// `index.d.ts` is the types entry (package.json `types`): the converter reads
// the component list AND each component's props from it. Only the card set is
// re-exported, so sub-parts (CardHeader, DialogTrigger, …) stay importable
// from the bundle without each claiming its own preview card.
const cfg = JSON.parse(readFileSync('.design-sync/config.json', 'utf8'));
const cards = Object.entries(cfg.componentSrcMap ?? {});
const byModule = new Map();
for (const [name, file] of cards) {
  const mod = './' + file.replace(/\.tsx$/, '');
  if (!byModule.has(mod)) byModule.set(mod, []);
  byModule.get(mod).push(name);
}
writeFileSync(
  'dist/types/index.d.ts',
  '// GENERATED by .design-sync/regen.mjs — types entry for the design-system sync.\n' +
    [...byModule.entries()]
      .sort()
      .map(([mod, names]) => `export { ${names.sort().join(', ')} } from "${mod}";`)
      .join('\n') +
    '\n',
);

// ── card grouping ────────────────────────────────────────────────────────
// The converter derives a component's group from its source directory, but
// `ui/` and `components/` are on its generic-name skip list, so all 28 shadcn
// primitives would collapse into "general" alongside Logo and ThemeToggle.
// Group is the picker's only navigation affordance, so it's set explicitly.
//
// The mechanism is a frontmatter-only `<Name>.md` in `cfg.docsDir`: the
// converter reads `category` from it, and because the body is empty it still
// synthesizes the real `.prompt.md` from the props + authored preview. A doc
// with actual prose would REPLACE that synthesis — so keep these stubs empty.
//
// A doc category only wins where the directory-derived group came out generic,
// which is precisely the `ui/` case ("ui" and "components" are both on the
// converter's skip list, so those land in "general"). Everything else already
// groups by its own directory — app/, attachments/, files/, icons/,
// marketing/ — which mirrors the repo and needs no override. Listing those
// here would write files that look authoritative but are silently ignored.
const GROUPS = {
  primitives: [
    'AlertDialog', 'Avatar', 'AvatarGroup', 'Badge', 'Button', 'Calendar', 'Card', 'Checkbox',
    'ContextMenu', 'DatePicker', 'Dialog', 'DropdownMenu', 'EmojiPicker', 'Input', 'Kbd', 'Label',
    'PasswordInput', 'Popover', 'ScrollArea', 'Select', 'Separator', 'Sheet', 'Skeleton', 'Switch',
    'Table', 'Tabs', 'Textarea', 'Toaster', 'Tooltip',
  ],
  // Directly under src/components/, so no directory segment to group by.
  brand: ['Logo', 'ThemeToggle'],
};

const grouped = new Map();
for (const [group, names] of Object.entries(GROUPS)) {
  for (const n of names) {
    if (grouped.has(n)) throw new Error(`[REGEN] ${n} is in two groups`);
    grouped.set(n, group);
  }
}
const unknown = [...grouped.keys()].filter((n) => !cfg.componentSrcMap?.[n]);
if (unknown.length) {
  console.error(`[REGEN] GROUPS names that are not cards: ${unknown.join(', ')}`);
  process.exit(1);
}

rmSync('.design-sync/docs', { recursive: true, force: true });
mkdirSync('.design-sync/docs', { recursive: true });
for (const [name, group] of grouped) {
  writeFileSync(`.design-sync/docs/${name}.md`, `---\ncategory: ${group}\n---\n`);
}

console.error(
  `[REGEN] ${FILES.length} files, ${owner.size} exports, ${stubCount} action stubs, ` +
    `${cards.length} typed cards, ${grouped.size} regrouped ` +
    `→ ds-entry.ts + .cache/{tailwind.css,stubs/} + dist/types/ + docs/`,
);
